language: shell
os: linux

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - bash .travis/main.sh

install:
  - docker pull shinau/candycbt:latest
  - docker run -d --name candycbt-ols -p 80:80 -p 443:443 -p 7080:7080 -p 8080:8080 shinau/candycbt:latest
before_script:
  - docker image ls
  - sleep 10

script:  
  - bash .travis/verify.sh

after_script:
  - docker container stop candycbt-ols
  - docker container rm candycbt-ols





