version: '3'
services:
  mysql:
    image: shinau/candycbt:db
    logging:
      driver: none
    command: --max_allowed_packet=256M
    restart: always
    networks:
      - default
  web:
    image: shinau/candycbt:web
    logging:
      driver: none
    volumes:
      - ./logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 7080:7080
    restart: always
    networks:
      - default
  pma:
    image: bitnami/phpmyadmin:5.2.0-debian-11-r43
    ports:
      - 8080:8080
      - 8443:8443
    environment:
        DATABASE_HOST: mysql
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge