name: docker-build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          docker pull shinau/candycbt
          docker container -d --name candycbt -p 80:80 -p 443:443 -p 7080:7080 -p 8080:8080 shinau/candycbt
          docker container ls | grep candycbt
          sleep 10
      - name: Verify
        run: bash .travis/verify.sh    
      - name: Clean up 
        run: |
         docker-compose stop
         docker-compose rm -f            
